# Turns Natural Earth land outlines (public domain, naturalearthdata.com) into worldmap.js,
# the dotted world map shown by `travel`.
# Usage: python3 tools/worldmap.py [columns]   — needs Pillow and NumPy
import json, os, sys
import numpy as np
from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COLS = int(sys.argv[1]) if len(sys.argv) > 1 else 120
LAT_MAX, LAT_MIN = 80, -72          # keep the Antarctic coast, crop the far Arctic and the pole
SS = 8                              # supersampling per dot, for partial-coverage dots
cell_deg = 360 / COLS
ROWS = round((LAT_MAX - LAT_MIN) / cell_deg)

W, H = COLS * SS, ROWS * SS
img = Image.new("L", (W, H), 0)
draw = ImageDraw.Draw(img)
project = lambda lon, lat: ((lon + 180) / 360 * W, (LAT_MAX - lat) / (LAT_MAX - LAT_MIN) * H)

geo = json.load(open(os.path.join(ROOT, "tools", "data", "ne_110m_land.geojson")))
for f in geo["features"]:
    g = f["geometry"]
    polys = [g["coordinates"]] if g["type"] == "Polygon" else g["coordinates"]
    for poly in polys:
        draw.polygon([project(*pt) for pt in poly[0]], fill=255)
        for hole in poly[1:]:
            draw.polygon([project(*pt) for pt in hole], fill=0)

cover = np.asarray(img, dtype=float).reshape(ROWS, SS, COLS, SS).mean(axis=(1, 3)) / 255
data = ["".join("0123456789"[min(9, int(round(v * 9)))] for v in row) for row in cover]

open(os.path.join(ROOT, "worldmap.js"), "w").write(
    "// Generated by tools/worldmap.py from Natural Earth land data. One digit (0-9) per dot = land coverage.\n"
    f"const WORLDMAP = {json.dumps({'cols': COLS, 'rows': ROWS, 'latMax': LAT_MAX, 'latMin': LAT_MIN, 'data': data}, indent=1)};\n")

# preview
S = 8
prev = Image.new("RGB", (COLS * S, ROWS * S), (13, 18, 36))
d = ImageDraw.Draw(prev)
for r, row in enumerate(data):
    for c, ch in enumerate(row):
        v = int(ch) / 9
        if v <= 0: continue
        rad = S / 2 * (0.25 + 0.6 * v)
        d.ellipse([c*S + S/2 - rad, r*S + S/2 - rad, c*S + S/2 + rad, r*S + S/2 + rad], fill=(200, 185, 255))
prev.save(os.path.join(ROOT, "tools", "worldmap-preview.png"))
print(COLS, ROWS)
